### ISSUE TITLE
Net::ReadTimeout   Error

### ISSUE THREAD

**Issue by chenyurong** [wmmc/codeschool-video-downloader#1]
I use your ruby code to download CodeSchool video.
At first everything is right, but when I run 

```
ruby code_school_scraper.rb *your_username* *your_password*
```

in the console, I show me the error:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:158:in `rescue in rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
```

you can see the full logs at the end. And I can't figure it out, can you help me to figure out?  
Is it the problem of network?  BTW, I'm in ShenZhen China. THANKS.

HERE IS FULL LOGS:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:158:in `rescue in rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:152:in `rbuf_fill'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:134:in `readuntil'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:144:in `readline'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:39:in `read_status_line'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:28:in `read_new'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1406:in `block in transport_request'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1403:in `catch'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1403:in `transport_request'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1376:in `request'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1369:in `block in request'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:852:in `start'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1367:in `request'
    from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/http/default.rb:107:in `response_for'
    from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/http/default.rb:58:in `request'
    from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/bridge.rb:657:in `raw_execute'
    from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/bridge.rb:635:in `execute'
    from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/bridge.rb:133:in `get'
    from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/common/navigation.rb:33:in `to'
    from /Library/Ruby/Gems/2.0.0/gems/watir-webdriver-0.8.0/lib/watir-webdriver/browser.rb:76:in `goto'
    from code_school_scraper.rb:25:in `login'
    from code_school_scraper.rb:14:in `initialize'
    from code_school_scraper.rb:115:in `new'
    from code_school_scraper.rb:115:in `<main>'
```

**Comment by will-clarke** [comment]
Thanks for trying this out! You are the first person who's ever commented on any of my programs on Github :smiley: 

I suppose the first thing to check is that you can actually reach this URL in your browser: http://www.codeschool.com/users/sign_in 

If that's fine, then are you able to see the site pop up in firefox? And did your username & password get accepted?

**Comment by chenyurong** [comment]
I can reach the URL and when I run 

```
ruby code_school_scraper.rb *your_username* *your_password*
```

I can see the site pop up in Firefox but it just stay on that sign in page and no any other action. The username and password is fine. I had open the website and login with the username and password manually.

one of my friend in Singapore had download successfully with your code, but I failed. I have try several time but it doesn't work.

**Comment by will-clarke** [comment]
Hmmmm... that's strange. It should try to enter your details once firefox pops up.

Other people have had problems with Net::ReadTimeout for Selenium. You could try using this code:

``` ruby
client = Selenium::WebDriver::Remote::Http::Default.new
client.timeout = 180 # seconds – default is 60

@browser = Watir::Browser.new :firefox, :http_client => client
```

to replace line 12. (@browser....... )

Have a look at this: http://stackoverflow.com/questions/9014121/how-do-i-change-the-page-load-timeouts-in-watir-webdriver-timeout-in-click-met

Hope that helps
