### ISSUE TITLE
Unable to find Mozilla geckodriver

### ISSUE THREAD

**Issue by N4d4** [wmmc/codeschool-video-downloader#10]
When I launch the script, it shows me this error..

```shell
/var/lib/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/firefox.rb:58:in `driver_path':         Unable to find Mozilla geckodriver. Please download the server from        https://github.com/mozilla/geckodriver/releases and place it        somewhere on your PATH. More info at https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver. (Selenium::WebDriver::Error::WebDriverError)
	from /var/lib/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/firefox/w3c_bridge.rb:30:in `initialize'
	from /var/lib/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/common/driver.rb:52:in `new'
	from /var/lib/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/common/driver.rb:52:in `for'
	from /var/lib/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver.rb:82:in `for'
	from /var/lib/gems/2.3.0/gems/watir-webdriver-0.9.9/lib/watir-webdriver/browser.rb:46:in `initialize'
	from code_school_scraper.rb:12:in `new'
	from code_school_scraper.rb:12:in `initialize'
	from code_school_scraper.rb:163:in `new'
	from code_school_scraper.rb:163:in `<main>'
```
how can I fix this?

**Comment by effexts** [comment]
Read carefully the error. It shows you the solution itself. Download Mozilla geckodriver.

**Comment by will-clarke** [comment]
Thanks @effexts. 
I've updated this so there shouldn't be any problems (especially if you `brew install chromedriver`)
