### ISSUE TITLE
Runtime.executionContextCreated has invalid 'context'

### ISSUE THREAD

**Issue by flyingboy007** [wmmc/codeschool-video-downloader#12]
Getting below error on running  `ruby code_school_scraper.rb *your_username* *your_password*`

```
/home/workstation/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require': `require "watir-webdriver"` is deprecated. Please, use `require "watir"`.
/home/workstation/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok': unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"32137.1","isDefault":true},"id":1,"name":"","origin":"://"} (Selenium::WebDriver::Error::UnknownError)
  (Session info: chrome=54.0.2840.100)
  (Driver info: chromedriver=2.9.248304,platform=Linux 4.4.0-47-generic x86_64)
	from /home/workstation/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
	from /home/workstation/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/common.rb:81:in `new'
	from /home/workstation/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/common.rb:81:in `create_response'
	from /home/workstation/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/default.rb:86:in `request'
	from /home/workstation/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from /home/workstation/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:653:in `raw_execute'
	from /home/workstation/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:631:in `execute'
	from /home/workstation/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/bridge.rb:136:in `get'
	from /home/workstation/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/common/navigation.rb:32:in `to'
	from /home/workstation/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/watir-6.0.2/lib/watir/browser.rb:78:in `goto'
	from code_school_scraper.rb:24:in `login'
	from code_school_scraper.rb:13:in `initialize'
	from code_school_scraper.rb:163:in `new'
	from code_school_scraper.rb:163:in `<main>'

```

**Comment by will-clarke** [comment]
I've just updated this this error should be fixed for you now.

If you've got homebrew installed, you should be able to simply `brew install chromedriver` to get this working now.

Let me know if you've still got problems!

**Comment by Guimove** [comment]
Hello,

I always have the same issue : 

```
/usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.2/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok': session not created exception (Selenium::WebDriver::Error::SessionNotCreatedError)
from unknown error: bad inspector message: {"method":"Page.loadEventFired","params":{"timestamp":72472,065488}}
  (Session info: chrome=54.0.2840.98)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.12.1 x86_64)
	from /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.2/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
	from /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.2/lib/selenium/webdriver/remote/http/common.rb:81:in `new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.2/lib/selenium/webdriver/remote/http/common.rb:81:in `create_response'
	from /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.2/lib/selenium/webdriver/remote/http/default.rb:86:in `request'
	from /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.2/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.2/lib/selenium/webdriver/remote/bridge.rb:647:in `raw_execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.2/lib/selenium/webdriver/remote/bridge.rb:109:in `create_session'
	from /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.2/lib/selenium/webdriver/remote/bridge.rb:69:in `initialize'
	from /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.2/lib/selenium/webdriver/chrome/bridge.rb:42:in `initialize'
	from /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.2/lib/selenium/webdriver/common/driver.rb:61:in `new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.2/lib/selenium/webdriver/common/driver.rb:61:in `for'
	from /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.2/lib/selenium/webdriver.rb:82:in `for'
	from /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.0.2/lib/watir/browser.rb:46:in `initialize'
	from codeschool_downloader.rb:17:in `new'
	from codeschool_downloader.rb:17:in `initialize'
	from codeschool_downloader.rb:256:in `new'
	from codeschool_downloader.rb:256:in `<main>'
```

I have the latest version of the code and followed the README instruction with the chromedriver installation.
